# Generated by Django 3.2 on 2021-04-28 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-created_at',)},
        ),
    ]
